services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  financial-api:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - DEBUG=True
      - REDIS_URL=redis://redis:6379/1
      - OFDA_API_BASE_URL=http://host.docker.internal:8000
    volumes:
      - .:/app
    command: >
      sh -c "
        python manage.py collectstatic --noinput &&
        gunicorn --bind 0.0.0.0:8001 --workers 4 --timeout 120 --reload src.config.wsgi:application
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
